// <auto-generated>
// This file was generated by the Cadenza compiler. Do not edit manually.
// Direct .g.cs generation - explicit over implicit compilation

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;
using Microsoft.JSInterop;
using System.Text.Json.Serialization;

namespace CadenzaWebApp.Components.Pages
{
    [Microsoft.AspNetCore.Components.RouteAttribute("/counter")]
    public class Counter : ComponentBase
    {

    // Component State
    private int _count = 0;

        // Service Injections
        [Inject, JsonIgnore]
        private IJSRuntime DOMService { get; set; } = default!;


        // Event Handlers
        private void handle_increment()
        {
            _count = (_count + 1);
            StateHasChanged();
        }

        private void handle_decrement()
        {
            _count = (_count - 1);
            StateHasChanged();
        }


        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "div");
            builder.AddAttribute(1, "class", "semantic: padding:lg, flex-column, center");
            builder.AddAttribute(2, "style", "semantic: background:background-alt");
            builder.OpenElement(3, "h1");
            builder.AddAttribute(4, "class", "semantic: text:primary, margin:md");
            builder.AddContent(5, ("Counter: " + _count.ToString()));
            builder.CloseElement();
            builder.OpenElement(6, "div");
            builder.AddAttribute(7, "class", "semantic: flex, gap:md");
            builder.OpenElement(8, "button");
            builder.AddAttribute(9, "onclick", EventCallback.Factory.Create(this, handle_increment));
            builder.AddAttribute(10, "class", "btn-primary");
            builder.AddContent(11, "Increment");
            builder.CloseElement();
            builder.OpenElement(12, "button");
            builder.AddAttribute(13, "onclick", EventCallback.Factory.Create(this, handle_decrement));
            builder.AddAttribute(14, "class", "btn-secondary");
            builder.AddContent(15, "Decrement");
            builder.CloseElement();
            builder.CloseElement();
            builder.OpenElement(16, "div");
            builder.AddAttribute(17, "class", "semantic: margin:md, text:center");
            builder.OpenElement(18, "h3");
            builder.AddAttribute(19, "class", "text-muted");
            builder.AddContent(20, "Status: OK");
            builder.CloseElement();
            builder.CloseElement();
            builder.CloseElement();
        }
    }

}


