// Cadenza Core Compiler - Blazor Component Generator
// Main component generation orchestration using refactored components

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Cadenza.Core;

// =============================================================================
// BLAZOR COMPONENT GENERATOR
// =============================================================================

/// <summary>
/// Generates Blazor ComponentBase classes from Cadenza UI component ASTs using RenderTreeBuilder API
/// </summary>
public class BlazorComponentGenerator
{
    private readonly StringBuilder _classContent = new();
    private readonly HashSet<string> _usedNamespaces = new();
    private readonly Dictionary<string, string> _stateVariables = new();
    private readonly List<string> _eventHandlers = new();
    private readonly ExpressionGenerator _expressionGenerator;
    private readonly RenderTreeGenerator _renderTreeGenerator;

    public BlazorComponentGenerator()
    {
        _expressionGenerator = new ExpressionGenerator(_stateVariables, _classContent);
        _renderTreeGenerator = new RenderTreeGenerator(_classContent, _expressionGenerator);
    }
    
    /// <summary>
    /// Generates a Blazor ComponentBase class from a Cadenza ComponentDeclaration
    /// </summary>
    public string GenerateBlazorComponent(ComponentDeclaration component, bool includeRouteAttribute = true)
    {
        _classContent.Clear();
        _usedNamespaces.Clear();
        _stateVariables.Clear();
        _eventHandlers.Clear();
        _renderTreeGenerator.ResetSequence();

        // Add required namespaces
        AddRequiredNamespaces(component);
        
        // Generate class content
        GenerateComponentClass(component, includeRouteAttribute);
        
        // Combine using statements and class
        var result = new StringBuilder();
        result.AppendLine("// <auto-generated>");
        result.AppendLine("// This file was generated by the Cadenza compiler. Do not edit manually.");
        result.AppendLine("// Direct .g.cs generation - explicit over implicit compilation");
        result.AppendLine();
        
        foreach (var ns in _usedNamespaces.OrderBy(n => n))
        {
            result.AppendLine($"using {ns};");
        }
        result.AppendLine();
        
        // Add proper namespace for component discovery (matches assembly name)
        result.AppendLine("namespace CadenzaWebApp.Components.Pages");
        result.AppendLine("{");
        
        // Add indentation to all class content lines
        var indentedClassContent = string.Join("\n", 
            _classContent.ToString().Split('\n')
                .Select(line => string.IsNullOrWhiteSpace(line) ? line : "    " + line));
        result.Append(indentedClassContent);
        
        result.AppendLine();
        result.AppendLine("}"); // Close namespace
        
        return result.ToString();
    }

    /// <summary>
    /// Adds required namespaces for the component
    /// </summary>
    private void AddRequiredNamespaces(ComponentDeclaration component)
    {
        _usedNamespaces.Add("Microsoft.AspNetCore.Components");
        _usedNamespaces.Add("Microsoft.AspNetCore.Components.Rendering");
        _usedNamespaces.Add("System.Text.Json.Serialization");
        
        if (component.Effects != null)
        {
            foreach (var effect in component.Effects)
            {
                var ns = TypeMapper.GetEffectNamespace(effect);
                if (ns != null)
                {
                    _usedNamespaces.Add(ns);
                }
            }
        }
    }
    
    /// <summary>
    /// Generates the complete component class
    /// </summary>
    private void GenerateComponentClass(ComponentDeclaration component, bool includeRouteAttribute = true)
    {
        // Add RouteAttribute for Blazor Router (equivalent to @page directive) only if requested
        if (includeRouteAttribute)
        {
            // Use proper route format with leading slash
            _classContent.AppendLine($"[Microsoft.AspNetCore.Components.RouteAttribute(\"/{component.Name.ToLower()}\")]");
        }
        _classContent.AppendLine($"public class {component.Name} : ComponentBase");
        _classContent.AppendLine("{");
        
        // Generate parameters
        GenerateParameters(component.Parameters);
        
        // Generate state fields
        GenerateStateFields(component.State);
        
        // Generate service injections
        GenerateServiceInjections(component.Effects);
        
        // Generate lifecycle methods
        GenerateLifecycleMethods(component);
        
        // Generate event handlers
        GenerateEventHandlers(component.Events);
        
        // Generate BuildRenderTree method
        _renderTreeGenerator.GenerateBuildRenderTreeMethod(component.RenderBlock);
        
        _classContent.AppendLine("}");
    }

    /// <summary>
    /// Generates component parameters as [Parameter] properties
    /// </summary>
    private void GenerateParameters(List<Parameter>? parameters)
    {
        if (parameters == null || parameters.Count == 0) return;
        
        _classContent.AppendLine();
        _classContent.AppendLine("    // Component Parameters");
        
        foreach (var param in parameters)
        {
            var blazorType = TypeMapper.MapCadenzaTypeToBlazor(param.Type);
            _classContent.AppendLine($"    [Parameter] public {blazorType} {param.Name} {{ get; set; }}");
            
            // Note: Default values for parameters are not supported in the current AST
            // This would require extending the Parameter record to include DefaultValue property
        }
    }

    /// <summary>
    /// Generates state fields as private backing fields with public properties
    /// </summary>
    private void GenerateStateFields(List<StateDeclaration>? states)
    {
        if (states == null || states.Count == 0) return;
        
        _classContent.AppendLine();
        _classContent.AppendLine("    // Component State");
        
        foreach (var state in states)
        {
            var blazorType = TypeMapper.MapCadenzaTypeToBlazor(state.Type);
            var fieldName = $"_{state.Name}";
            var propertyName = state.Name;
            
            // Store mapping for later use in expressions
            _stateVariables[state.Name] = blazorType;
            
            // Generate private backing field
            if (state.InitialValue != null)
            {
                var initialValue = _expressionGenerator.GenerateExpression(state.InitialValue);
                _classContent.AppendLine($"    private {blazorType} {fieldName} = {initialValue};");
            }
            else
            {
                _classContent.AppendLine($"    private {blazorType} {fieldName};");
            }
            
            // Generate public property with StateHasChanged notification
            _classContent.AppendLine($"    public {blazorType} {propertyName}");
            _classContent.AppendLine("    {");
            _classContent.AppendLine($"        get => {fieldName};");
            _classContent.AppendLine("        set");
            _classContent.AppendLine("        {");
            _classContent.AppendLine($"            {fieldName} = value;");
            _classContent.AppendLine("            StateHasChanged();");
            _classContent.AppendLine("        }");
            _classContent.AppendLine("    }");
        }
    }

    /// <summary>
    /// Generates service injection properties for effects
    /// </summary>
    private void GenerateServiceInjections(List<string>? effects)
    {
        if (effects == null || effects.Count == 0) return;
        
        _classContent.AppendLine();
        _classContent.AppendLine("    // Injected Services");
        
        foreach (var effect in effects)
        {
            var serviceType = TypeMapper.MapEffectToBlazorService(effect);
            _classContent.AppendLine($"    [Inject] public {serviceType}? {effect}Service {{ get; set; }}");
        }
    }

    /// <summary>
    /// Generates lifecycle methods like OnMount
    /// </summary>
    private void GenerateLifecycleMethods(ComponentDeclaration component)
    {
        if (component.OnMount != null)
        {
            _classContent.AppendLine();
            _classContent.AppendLine("    protected override async Task OnInitializedAsync()");
            _classContent.AppendLine("    {");
            _classContent.AppendLine("        await base.OnInitializedAsync();");
            
            _expressionGenerator.GenerateStatements(component.OnMount, "        ");
            
            _classContent.AppendLine("    }");
        }
    }

    /// <summary>
    /// Generates event handler methods
    /// </summary>
    private void GenerateEventHandlers(List<EventHandler>? events)
    {
        if (events == null || events.Count == 0) return;
        
        _classContent.AppendLine();
        _classContent.AppendLine("    // Event Handlers");
        
        foreach (var eventHandler in events)
        {
            _classContent.AppendLine($"    private async Task {eventHandler.Name}()");
            _classContent.AppendLine("    {");
            
            foreach (var statement in eventHandler.Body)
            {
                _expressionGenerator.GenerateStatements(statement, "        ");
            }
            
            _classContent.AppendLine("    }");
            
            // Track event handlers for reference
            _eventHandlers.Add(eventHandler.Name);
        }
    }
}

/// <summary>
/// Enhanced Blazor Generator with CSS generation capabilities
/// This is the main entry point used by the WebServer components
/// </summary>
public class EnhancedBlazorGenerator
{
    private readonly BlazorComponentGenerator _componentGenerator;
    private readonly CadenzaSemanticStyling _semanticStyling;

    public EnhancedBlazorGenerator()
    {
        _componentGenerator = new BlazorComponentGenerator();
        _semanticStyling = new CadenzaSemanticStyling();
    }

    /// <summary>
    /// Generates a Blazor ComponentBase class from a Cadenza ComponentDeclaration
    /// </summary>
    public string GenerateBlazorComponent(ComponentDeclaration component, bool includeRouteAttribute = true)
    {
        return _componentGenerator.GenerateBlazorComponent(component, includeRouteAttribute);
    }

    /// <summary>
    /// Generates semantic CSS for a component using the semantic styling system
    /// </summary>
    public string GenerateComponentCSS(ComponentDeclaration component)
    {
        return _semanticStyling.ProcessComponentStyling(component);
    }
}